### ISSUE TITLE
 About YOHO  dataset

### ISSUE THREAD

**Issue by mcf199446** [tobiasfshr/gmm-ubm-speaker-identification-verification#1]
Hello! I'm a graduate student from China. After reading your paper, I was deeply inspired, so I wanted to study your code, but no data set was always running out. I found it for a long time and didn't find it. So can you provide me with a data set?

**Comment by tobiasfshr** [comment]
Well, I got the dataset from my lecturer, and it seems that you must have a license to download it:
https://catalog.ldc.upenn.edu/ldc94s16
However,  your university could be able to provide you with the dataset. Otherwise, you will have to use another dataset.

**Comment by mcf199446** [comment]
Thank you for your reply.My school does not have permission to enter the site. I do not know if it is not convenient for me to download your good data set. Thank you very much! My mailbox is 1924294998@qq.com
