### ISSUE TITLE
Testing Program Discovery Vulnerabilities 

### ISSUE THREAD

**Issue by huanying3200** [tobiasfshr/gmm-ubm-speaker-identification-verification#2]
Warning: Matrix approaching singular values or scaling errors. The results may not be accurate. RCOND = 4.569468e-19            
> In getLog Likelihood (line 30)            
In MStep (line 73)           
In EST Gauss MixEM (line 40)           
In main (line 76)

**Comment by tobiasfshr** [comment]
Hey, thanks for pointing that out. The problem lies within the division of "meansDiff / covariance". When you have a too small covariance, the divison fails. Hence, i would set a minimum covariance if you want to mitigate the problem.
